"""Author the 3 public-dev Track-3 units (card + scenario + reference trace + events).

Each public scenario in ``regression_suite/scenarios/`` becomes a self-contained unit under
``units/`` — the participant-facing practice package AND the Dev-phase scoring input (the
shared ``score.py`` reads ``card.toml`` + ``trace.parquet`` per unit). Each unit gets a real
manifest.json (sha256/bytes for every file) and its uuid4 canary is read from the pinned
``canary_registry.json`` — never derived from a formula (Agenthon rule 4).

Usage:  python scripts/build_public_units.py
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCEN = REPO / "regression_suite" / "scenarios"
REFS = REPO / "regression_suite" / "reference_traces"
UNITS = REPO / "units"
REGISTRY = REPO / "canary_registry.json"
FROZEN_CEILINGS = {"ks": 0.08, "acf_abs_l2": 0.12, "hill_abs": 1.5, "depth_js": 0.10}

# Every scenario file in regression_suite/scenarios/ becomes a unit; the unit id is derived
# from the filename: <stem>.json -> t3-<stem-with-dashes>. A scenario with no generated
# reference trace yet is skipped (build its reference through the baseline first).


def _sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_canary(unit_id: str) -> str:
    units = json.loads(REGISTRY.read_text())["units"]
    if unit_id not in units:
        raise SystemExit(
            f"CANARY: {unit_id} missing from {REGISTRY.name} — register a fresh uuid4 first"
        )
    return units[unit_id]


def _write_manifest(unit_dir: Path, unit_id: str, roles: dict[str, str]) -> None:
    """Emit manifest.json with real sha256 + bytes for every file in the unit."""
    files = []
    for path in sorted(unit_dir.iterdir()):
        if path.name == "manifest.json":
            continue
        files.append(
            {
                "path": path.name,
                "role": roles.get(path.name, "fixture"),
                "license": "CC-BY-4.0",
                "sha256": _sha256(path),
                "split": "public-dev",
                "redistributable": True,
                "bytes": path.stat().st_size,
            }
        )
    (unit_dir / "manifest.json").write_text(
        json.dumps(
            {
                "manifest_version": "2.0",
                "unit_id": unit_id,
                "generated_by": "scripts/build_public_units.py",
                "files": files,
                "notes": f"Public-dev Track-3 practice unit {unit_id}; real sha256/bytes for every file.",
            },
            indent=2,
        )
        + "\n"
    )


def _card(
    unit_id: str, scen: dict, canary: str, trace_sha: str, events_sha: str
) -> str:
    # Comments belong here rather than inside the returned template: anything written into the
    # f-string is emitted into every generated card, and the committed cards do not carry it.
    # `[environment] gpu = true` is uniform across every Track 3 unit -- a throughput ranking needs
    # constant hardware rather than a per-unit-optimal allocation, and using the device is optional.
    # tests/test_unit_cards.py fails the build if the emitted block drifts from the committed cards.
    fam = scen["scenario_family"]
    tier = scen.get("tolerance", {}).get("tier", "A")
    # Difficulty is derived from the semantic tier, not author-assigned. Tier-A units require
    # bit-exact reproduction (fill sequence + latency-causal ledger), which forbids the
    # approximations and event reordering that buy GPU speed — a naive/fast port is rejected by
    # the g3 gate — so an accelerated-yet-faithful submission is "hard". Tier-B units are graded
    # on statistical tolerance (KS / stylized-fact ceilings), which admits an accelerable
    # approximation band, so they are "medium".
    difficulty = "hard" if tier == "A" else "medium"
    # The message ledger is mandatory by CARD DECLARATION, not by whether a reference
    # message_trace.parquet happens to exist -- a missing reference file used to switch the
    # latency-causality gate off silently for that unit. Throughput-scale is the one family whose
    # single-market units ship no ledger; everything else requires one. Mirrored in
    # scripts/build_batch_units.py and in the sealed generator, per AGENTS.md.
    requires_ledger = "false" if fam == "throughput-scale" else "true"
    ceil = "\n".join(f"{k:<10} = {v}" for k, v in FROZEN_CEILINGS.items())
    return f"""# QFBench 2.0 task-card v2 — Track 3 public-dev unit (generated by scripts/build_public_units.py)
schema_version = "2.0"

[task]
id              = "{unit_id}"
track           = "simulation"
title           = "Public practice scenario: {unit_id}"
split           = "public-dev"
scenario_family = "{fam}"
scenario_file   = "scenario.json"
description      = "Public Track-3 practice scenario ({fam}). Config + reference answer provided; reproduce the reference trace within tolerance. Your simulator MUST write BOTH trace.parquet and the message-level kernel ledger message_trace.parquet to /output — the ledger is a required output and gates the message-semantics (latency-causality) admissibility check."

[metadata]
author_name = "QFBench2 Organising Committee"
difficulty  = "{difficulty}"
category    = "{fam}"
tags        = ["simulation", "lob", "{fam}"]

[contamination]
canary_guid = "{canary}"

[provenance]
license                 = "CC-BY-4.0"
data_source             = "organizer-maintained ABIDES fork (BSD-3) reference traces"
data_cutoff             = ""
public_release_date     = "2026-07-20"
redistributable         = true
manifest                = "manifest.json"
abides_fork_commit      = "f9cbe51342b7dedd9587e4e069040d68a5c6477f"
reference_trace_sha256  = "{trace_sha}"
reference_events_sha256 = "{events_sha}"

[scoring]
verifier            = "t3.semantic_stylized"
metric              = "events_per_sec"
admissibility_gates = ["g0_integrity", "g1_schema", "g2_cutoff_resource", "g3_domain_semantics"]

[scoring.params]
semantic_tier          = "{tier}"
timestamp_tolerance_ns = 1000
# Whether the message-level kernel ledger is a required output for this unit. Declared
# here rather than inferred from whether a reference message_trace.parquet happens to
# exist: a missing reference file used to switch the latency-causality gate OFF silently.
requires_message_ledger = {requires_ledger}

[scoring.params.stylized_fact_ceilings]
{ceil}

[environment]
cpus    = 4
memory  = "16G"
gpu     = true
network = "none"
disk    = "10G"

[io]
input_schema         = "sim_scenario.schema.json"
output_trace_cols    = ["t_ns", "agent_id", "msg_type", "side", "price", "size", "order_id"]
output_events_fields = ["scenario_id", "n_events", "wall_clock_sec", "events_per_sec", "seed", "trace_sha256"]
"""


def main() -> int:
    built = []
    for scen_path in sorted(SCEN.glob("*.json")):
        scen = json.loads(scen_path.read_text())
        if "scenario_id" not in scen:
            continue  # not a scenario file (e.g. a scenarios index)
        sid = scen["scenario_id"]
        unit_id = "t3-" + scen_path.stem.replace("_", "-")
        ref = REFS / sid
        trace, events = ref / "trace.parquet", ref / "events.json"
        if not trace.exists():
            print(f"  skip {unit_id}: no reference trace at {ref}")
            continue
        unit = UNITS / unit_id
        unit.mkdir(parents=True, exist_ok=True)
        shutil.copy(scen_path, unit / "scenario.json")
        shutil.copy(trace, unit / "trace.parquet")
        shutil.copy(events, unit / "events.json")
        roles = {
            "card.toml": "fixture",
            "scenario.json": "scenario",
            "trace.parquet": "reference",
            "events.json": "reference",
        }
        # v2: carry the message-level enriched trace when the reference has one, so the
        # message-semantics gate (g3 block c) can run against this unit.
        msg_trace = ref / "message_trace.parquet"
        if msg_trace.exists():
            shutil.copy(msg_trace, unit / "message_trace.parquet")
            roles["message_trace.parquet"] = "reference"
        canary = _load_canary(unit_id)
        (unit / "card.toml").write_text(
            _card(unit_id, scen, canary, _sha256(trace), _sha256(events))
        )
        _write_manifest(unit, unit_id, roles)
        built.append(unit_id)
    print("built public units:", built)
    print(
        "next: qfbench2 card validate units/<id>  and  qfbench2 manifest verify / assert-public-safe"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
