"""Author the public BatchMarketSim (GB) units — batched multi-scenario practice packages.

Each batch unit bundles N independent single-market sub-scenarios plus their ISOLATED reference
traces (generated by running each sub alone through the ledger baseline). A submission runs the
batch verb `simulate-batch` over ``scenarios/`` and must reproduce every sub's isolated reference;
a batch that leaks state across markets diverges on some sub and fails the isolation gate. The
aggregate events/sec across the batch is the throughput the family ranks.

Unit layout (self-contained; validate_units-compatible — card + manifest + unique canary):

    units/t3-gbatch-<name>/
      card.toml            scenario_family=throughput-scale (fam 6, Tier-A); [batch] batch=true, n=N
      batch.json           {"n": N, "subs": [{"sub","scenario_file","reference_trace_sha256",
                                              "reference_message_sha256","n_events"}]}
      scenarios/<sub>.json           N solver-facing sub-scenarios (only solver-facing artifacts)
      checks/reference_data/<sub>/trace.parquet + message_trace.parquet + events.json
                                     N isolated references
      manifest.json

Usage:  python scripts/build_batch_units.py        # regenerates every public gbatch unit
Reference generation uses the pinned ledger image (track3-abides-ledger:test), --network=none.
"""

from __future__ import annotations

import copy
import hashlib
import json
import subprocess
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UNITS = REPO / "units"
REGISTRY = REPO / "canary_registry.json"
IMAGE = "track3-abides-ledger:test"
FROZEN_CEILINGS = {"ks": 0.08, "acf_abs_l2": 0.12, "hill_abs": 1.5, "depth_js": 0.10}
PIN = "f9cbe51342b7dedd9587e4e069040d68a5c6477f"

# A light single-market sub-scenario base — batch value is N-parallelism, not per-market size, so
# each sub is kept modest (~10-15k events) to keep the shipped isolation references small.
_SUB_BASE = {
    "scenario_family": "throughput-scale",
    "schema_version": 2,
    "horizon_ns": 400_000_000,
    "agent_mix": {
        "NoiseTrader": 5,
        "ValueTrader": 2,
        "MarketMaker": 1,
        "MomentumTrader": 1,
    },
    "exchange_config": {
        "symbol": "SYM",
        "tick_size": 1,
        "lot_size": 1,
        "min_price": 1,
        "max_price": 1_000_000,
        "order_types_allowed": ["LIMIT", "MARKET", "CANCEL", "REPLACE"],
    },
    "oracle_config": {
        "type": "mean_reverting",
        "params": {
            "initial_price": 100_000,
            "kappa": 0.1,
            "sigma": 0.002,
            "dt_ns": 1_000_000,
            "noise_type": "gaussian",
            "jump_intensity": 0.0,
            "jump_sigma": 0.0,
        },
    },
    "latency_config": {
        "model": "log_normal",
        "params": {"mean_ns": 800, "sigma": 0.3, "min_ns": 100, "max_ns": 10_000_000},
    },
    "agent_configs": [
        {
            "agent_type": "NoiseTrader",
            "count": 5,
            "params": {
                "order_size_mean": 8,
                "order_size_std": 2,
                "arrival_rate_hz": 15.0,
                "price_offset_ticks": 4,
            },
        },
        {
            "agent_type": "ValueTrader",
            "count": 2,
            "params": {
                "order_size_mean": 25,
                "threshold_ticks": 2,
                "arrival_rate_hz": 5.0,
            },
        },
        {
            "agent_type": "MarketMaker",
            "count": 1,
            "params": {
                "spread_ticks": 3,
                "depth_levels": 4,
                "size_per_level": 12,
                "rebalance_interval_ns": 2_000_000,
            },
        },
        {
            "agent_type": "MomentumTrader",
            "count": 1,
            "params": {
                "order_size_mean": 15,
                "threshold_ticks": 2,
                "lookback": 5,
                "arrival_rate_hz": 6.0,
            },
        },
    ],
    "output_config": {
        "trace_cols": [
            "t_ns",
            "agent_id",
            "msg_type",
            "side",
            "price",
            "size",
            "order_id",
        ],
        "events_fields": [
            "scenario_id",
            "n_events",
            "wall_clock_sec",
            "events_per_sec",
            "seed",
            "trace_sha256",
        ],
        "snapshot_interval_ns": 0,
    },
    "tolerance": {
        "tier": "A",
        "timestamp_tolerance_ns": 1000,
        "kendall_tau_floor": 0.999,
        "spread_bps_tolerance": 10.0,
        "stylized_fact_ceilings": FROZEN_CEILINGS,
    },
}


def _apply(overrides: dict) -> dict:
    cfg = copy.deepcopy(_SUB_BASE)
    for path, val in overrides.items():
        parts = path.split(".")
        node = cfg
        for p in parts[:-1]:
            node = node[int(p)] if p.isdigit() else node[p]
        last = parts[-1]
        if last.isdigit():
            node[int(last)] = val
        else:
            node[last] = val
    return cfg


def _det_seed(s: str) -> int:
    return int(hashlib.sha256(s.encode()).hexdigest(), 16) % (2**31 - 1) + 1


def _det_uuid(s: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "t3-v2-batchsub-" + s))


def _sha(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# Public batch designs (plan §3.3: 6 public). Vary batch size N, sub heterogeneity, and per-sub size.
# Each sub is (sub_name, overrides-on-_SUB_BASE). The sub seed/scenario_id are derived deterministically.
_DESIGNS: dict[str, list[tuple[str, dict]]] = {
    "gbatch-homog-4": [(f"sub_{i:02d}", {}) for i in range(4)],
    "gbatch-homog-8": [(f"sub_{i:02d}", {}) for i in range(8)],
    "gbatch-hetero-mix": [
        ("sub_00_noise", {"agent_configs.0.count": 8, "agent_mix.NoiseTrader": 8}),
        ("sub_01_value", {"agent_configs.1.count": 4, "agent_mix.ValueTrader": 4}),
        ("sub_02_mm", {"agent_configs.2.count": 3, "agent_mix.MarketMaker": 3}),
        (
            "sub_03_momentum",
            {"agent_configs.3.count": 4, "agent_mix.MomentumTrader": 4},
        ),
        ("sub_04_base", {}),
    ],
    "gbatch-varsize": [
        ("sub_00_short", {"horizon_ns": 250_000_000}),
        ("sub_01_med", {"horizon_ns": 400_000_000}),
        ("sub_02_long", {"horizon_ns": 600_000_000}),
        ("sub_03_med", {"horizon_ns": 450_000_000}),
    ],
    "gbatch-dense-3": [
        (f"sub_{i:02d}", {"agent_configs.0.params.arrival_rate_hz": 25.0})
        for i in range(3)
    ],
    "gbatch-many-6": [(f"sub_{i:02d}", {}) for i in range(6)],
}


def _run_isolated(scen_path: Path, out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    r = subprocess.run(
        [
            "docker",
            "run",
            "--rm",
            "--network=none",
            "-v",
            f"{scen_path}:/input/scenario.json:ro",
            "-v",
            f"{out_dir}:/output",
            IMAGE,
            "simulate",
            "--config",
            "/input/scenario.json",
            "--out",
            "/output/trace.parquet",
        ],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        raise RuntimeError(r.stderr[-400:])
    return json.loads((out_dir / "events.json").read_text())


def _card(unit_id: str, n: int, canary: str) -> str:
    """The unit's task card.

    Comments belong HERE, not inside the returned template: anything written into the f-string is
    emitted into every generated card, and the committed cards do not carry it, so a regeneration
    would rewrite all six. ``tests/test_unit_cards.py`` fails the build when the emitted
    ``[environment]`` block drifts from the committed cards.

    ``difficulty = "hard"``: the per-sub isolation gate is Tier-A (bit-exact reproduction of each
    sub's isolated reference), so a batched submission has to be faster AND faithful.
    ``[environment] gpu = true``: uniform across every Track 3 unit, because a throughput ranking
    needs constant hardware rather than a per-unit-optimal allocation. Using the device is optional.
    """
    ceil = "\n".join(f"{k:<10} = {v}" for k, v in FROZEN_CEILINGS.items())
    return f"""# QFBench 2.0 task-card v2 — Track 3 public-dev BATCH unit (scripts/build_batch_units.py)
schema_version = "2.0"

[task]
id              = "{unit_id}"
track           = "simulation"
title           = "Public batched multi-scenario package: {unit_id}"
split           = "public-dev"
scenario_family = "throughput-scale"
scenario_file   = "batch.json"
description      = "BatchMarketSim practice unit: {n} independent single-market sub-scenarios under scenarios/. Run the batch verb `simulate-batch --batch-dir /input/scenarios --out-dir /output`; each sub's output must reproduce its isolated reference (isolation gate), and the aggregate events/sec across the batch is the throughput metric. Your simulator MUST write per-sub trace.parquet + message_trace.parquet + events.json and a batch_events.json aggregate."

[metadata]
author_name = "QFBench2 Organising Committee"
difficulty  = "hard"
category    = "throughput-scale"
tags        = ["simulation", "lob", "throughput-scale", "batch"]

[contamination]
canary_guid = "{canary}"

[provenance]
license                 = "CC-BY-4.0"
data_source             = "organizer-maintained ABIDES fork (BSD-3) reference traces"
data_cutoff             = ""
public_release_date     = "2026-07-20"
redistributable         = true
manifest                = "manifest.json"
abides_fork_commit      = "{PIN}"

[batch]
batch = true
n     = {n}

[scoring]
verifier            = "t3.semantic_stylized"
metric              = "events_per_sec"
admissibility_gates = ["g0_integrity", "g1_schema", "g2_cutoff_resource", "g3_domain_semantics"]

[scoring.params]
semantic_tier          = "A"
timestamp_tolerance_ns = 1000
# Whether the message-level kernel ledger is a required output for this unit. Declared
# here rather than inferred from whether a reference message_trace.parquet happens to
# exist: a missing reference file used to switch the latency-causality gate OFF silently.
# Batch units are family 6 (throughput-scale): the ledger requirement is per SUB and is carried by
# each batch.json entry's reference_message_sha256, so the unit-level flag is false.
requires_message_ledger = false

[scoring.params.stylized_fact_ceilings]
{ceil}

[environment]
cpus    = 4
memory  = "16G"
gpu     = true
network = "none"
disk    = "10G"
"""


def _write_manifest(unit_dir: Path, unit_id: str) -> None:
    files = []
    for path in sorted(unit_dir.rglob("*")):
        if path.is_dir() or path.name == "manifest.json":
            continue
        rel = path.relative_to(unit_dir).as_posix()
        role = (
            "scenario"
            if rel.startswith("scenarios/")
            else "reference"
            if rel.startswith("checks/reference_data/")
            else "fixture"
        )
        files.append(
            {
                "path": rel,
                "role": role,
                "license": "CC-BY-4.0",
                "sha256": _sha(path),
                "split": "public-dev",
                "redistributable": True,
                "bytes": path.stat().st_size,
            }
        )
    (unit_dir / "manifest.json").write_text(
        json.dumps(
            {
                "manifest_version": "2.0",
                "unit_id": unit_id,
                "generated_by": "scripts/build_batch_units.py",
                "files": files,
                "notes": f"Public-dev BatchMarketSim unit {unit_id}; real sha256/bytes for every file.",
            },
            indent=2,
        )
        + "\n"
    )


def main() -> int:
    reg = json.loads(REGISTRY.read_text())
    built = []
    for name, subs in _DESIGNS.items():
        unit_id = "t3-" + name
        unit_dir = UNITS / unit_id
        # clean any prior build so removed subs don't linger
        if unit_dir.exists():
            import shutil

            shutil.rmtree(unit_dir)
        (unit_dir / "scenarios").mkdir(parents=True)
        (unit_dir / "checks" / "reference_data").mkdir(parents=True)
        batch_entries = []
        for sub_name, overrides in subs:
            slug = f"{name}-{sub_name}"
            cfg = _apply(overrides)
            cfg.update({"scenario_id": _det_uuid(slug), "seed": _det_seed(slug)})
            scen_path = unit_dir / "scenarios" / f"{sub_name}.json"
            scen_path.write_text(json.dumps(cfg, indent=2) + "\n")
            ref_dir = unit_dir / "checks" / "reference_data" / sub_name
            ev = _run_isolated(scen_path, ref_dir)
            batch_entries.append(
                {
                    "sub": sub_name,
                    "scenario_file": f"scenarios/{sub_name}.json",
                    "n_events": int(ev["n_events"]),
                    "reference_trace_sha256": _sha(ref_dir / "trace.parquet"),
                    "reference_message_sha256": _sha(ref_dir / "message_trace.parquet"),
                }
            )
        (unit_dir / "batch.json").write_text(
            json.dumps({"n": len(subs), "subs": batch_entries}, indent=2) + "\n"
        )
        canary = reg["units"].setdefault(unit_id, str(uuid.uuid4()))
        (unit_dir / "card.toml").write_text(_card(unit_id, len(subs), canary))
        _write_manifest(unit_dir, unit_id)
        total = sum(e["n_events"] for e in batch_entries)
        print(f"  built {unit_id}: {len(subs)} subs, {total} total events")
        built.append(unit_id)
    REGISTRY.write_text(json.dumps(reg, indent=2) + "\n")
    print(f"built {len(built)} public batch units: {built}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
